### ISSUE TITLE
Can't find package after installing dependency

### ISSUE THREAD

**Issue by javieranton-zz** [shannah/cn1-shared-files-lib#1]
My Common pom.xml:

![image](https://github.com/shannah/cn1-shared-files-lib/assets/11293898/e40b1c07-2a7d-4fef-97e1-af55af3bb3b6)

Importing:

![image](https://github.com/shannah/cn1-shared-files-lib/assets/11293898/89f0d12a-adc9-48eb-a54d-94fa8cd8e549)

Using (in same fie as imported):

![image](https://github.com/shannah/cn1-shared-files-lib/assets/11293898/d2421ebe-0ef7-4afb-b2b0-d8346541627c)

The lib was downloaded from maven as seen in output successfully

I also restarted Intellij a couple times

**Comment by shannah** [comment]
I don't see any obvious issues with what you've posted.  It clearly isn't picking up the dependency though as the imports are failing.  Try right clicking the pom.xml file (the root one), and select Maven > Reload Project.

**Comment by javieranton-zz** [comment]
Thanks
I ended up copying into my project (and adding multiple file selection support)
